### ISSUE TITLE
MacOS support and npm availability 

### ISSUE THREAD

**Issue by soufi** [voixen/voixen-vad#3]
Hi there,
I would like to test this package in my local environment but cannot install this tool using npm install ... could you please publish it ? 

I tried to clone the repo on my local machine then execute  `npm install`.

But it didn't work because the compilation fails with the following:

`clang: error: linker command failed with exit code 1 (use -v to see invocation)
make:  [Release/mpa.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: 'make' failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/Cellar/node6-lts/6.9.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Boulealf/Documents/Projects/PSA/smart-vehicle/dialog-client/nodejs/node_modules/voixen-vad
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok `

My environment : 
OS : MacOS 10.12 
Node: 6.9.1 
NPM: 3.10.8

Cheers.

**Comment by patlevin** [comment]
Hello soufi,

thank you for your interest in this library. I tried to replicate the issue by using Node 7 and forcing the use of clang via global settings in the .gyp file. By doing so I got a very similar error message. Since I don't use MacOS, I cannot replicate the exact issue but I can verify that neither clang nor Node 6.9 are the issue here.

I could force the use of clang and do a successful build by doing the following:

1.   open a new terminal and navigate to the local clone of the repository
2.   Tell GYP to use clang:
`export CC=/usr/bin/clang`
`export CXX=/usr/bin/clang++`
`export GYP_DEFINES="clang=1"`
3.   Run `npm install`

This worked with clang and Node 7. I will extend the GYP file to add MacOS-specific settings within the next few hours. I'll let you know once I got around to it.

PS: Tested on
OS: Linux Mint 16
Node: 7.2
Npm: 3.10.9
clang: 3.8

**Comment by patlevin** [comment]
Hi again,

I just pushed a new version that _should_ fix the issue. Could you please try the latest version and let me know if it worked?

Regards,
Pat

**Comment by soufi** [comment]
Hey,

Thanks for being reactive. 
I just tried the new version and also tried to export the variables to use CLANG. but it didn't work. I have the same issue. 

Best.

**Comment by patlevin** [comment]
Sorry to hear that - I'll have another look at the issue and get back to you soon.

EDIT: I just checked the nodejs discussion pages and found people reporting similar issues related to node-gyp with MacOS 10.10. The recommended solution is to upgrade Xcode and its tools to Xcode 7, running Xcode at least once and - provided there are still errors - doing the following from the command line: `cd /usr/local/lib sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib`

**Comment by soufi** [comment]
Finally what I did is cloning the repo in a lib directory and do npm install on it directly.
This package works fine on Linux. Thanks.
If you have a road map, maybe I can contribute. Cheers.
